# python -m pip install .

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "KAWASAKI-Chess"
dynamic = ["version"]
license = {text = "MIT License"}
requires-python = ">=3.11"
authors = [{name = "Jarosław Wierzbowski", email = "jaroslawierzbowski2001@gmail.com"}]
dependencies = [
    "chess >= 1.10.0",
    "py-cpuinfo >= 9.0.0",
    "pytz >= 2024.1",
    "flet >= 0.23.2"
]

[tool.ruff]
exclude = [
    "KAWASAKI",
    ".git",
    "piece_svg",
    "chess.db",
    ".gitignore",
    ".svg",
    ".txt",
]

line-length = 160
indent-width = 4
target-version = "py312"

[tool.ruff.lint]

select = [
        "W",
        "A",
        "PLC",
        "PLE",
        "PLW",
        "I",
        "ANN",
        "N",
        "E",
        "S",
        "F",
        "C",
        "UP",
        "YTT",
        "ASYNC",
        "FBT",
        "B",
        "COM",
        "DTZ",
        "EM",
        "EXE",
        "FA",
        "ISC",
        "ICN",
        "PIE",
        "T",
        "PYI",
        "Q",
        "RET",
        "SIM",
        "TID",
        "TCH",
        "INT",
        "ARG",
        "FIX",
        "PLR",
        "TRY",
        "FLY",
        "PERF",
        "FURB",
        "RUF"
]

ignore = [
    "W191",
    "FURB101",
    "FURB103",
    "FURB177",
    "TRY400",
    "PLE1205"
]

fixable = [
    "ALL"
]


unfixable = ["B"]

dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.setuptools]
py-modules = []