from kawachess.gripper import Gripper, State
from kawachess.robot import Cartesian, Move, Point, Robot


def calculate_point_to_move(algebraic_move: str, home: Point, z: float = 0.0) -> Point:
    x: int = ord(algebraic_move[0]) - ord("a")
    y: int = int(algebraic_move[1]) - 1
    return home.shift(algebraic_move, Cartesian(x=x * -37.3, y=y * -37.3, z=z))


gripper = Gripper(tty="COM4")
robot = Robot(ip="192.168.1.155", port=23)

# A1 = Point("a1", Cartesian(x=127.027, y=547.529, z=-207.811, o=168.942, a=178.064, t=-98.392))

#    131.747   555.219  -208.002   169.253   178.063  -100.462

A1 = Point("a1", Cartesian(x=134.255, y=554.503, z=-201.167, o=-175.344, a=179.571, t=-86.117))
# A1_up = A1.shift("a1_up", Cartesian(z=80.0))
# B2 = calculate_point_to_move("b2", A1, z=0.0)
# B2_up = B2.shift("a2_up", Cartesian(z=80.0))
# C3 = calculate_point_to_move("c3", A1, z=0.0)
# C3_up = C3.shift("a3_up", Cartesian(z=80.0))
# D4 = calculate_point_to_move("d4", A1, z=0.0)
# D4_up = D4.shift("a4_up", Cartesian(z=80.0))
# E5 = calculate_point_to_move("e5", A1, z=0.0)
# E5_up = E5.shift("a5_up", Cartesian(z=80.0))
# F6 = calculate_point_to_move("f6", A1, z=0.0)
# F6_up = F6.shift("a6_up", Cartesian(z=80.0))
# G7 = calculate_point_to_move("g7", A1, z=0.0)
# G7_up = G7.shift("a7_up", Cartesian(z=80.0))
# H8 = calculate_point_to_move("h8", A1, z=0.0)
# H8_up = H8.shift("h8_up", Cartesian(z=80.0))

# H1 = calculate_point_to_move("h1", A1, z=0.0)
# H1_up = H1.shift("h1_up", Cartesian(z=80.0))

# A8 = calculate_point_to_move("a8", A1, z=0.0)
# A8_up = A8.shift("a8_up", Cartesian(z=80.0))

robot.connect()
robot.add_point(A1)
robot.move
# robot.add_point(A1, H8, A1_up, H8_up, B2, B2_up, C3, C3_up, D4, D4_up, E5, E5_up, F6, F6_up, G7, G7_up, H1, H1_up, A8, A8_up)
# gripper.control(State.OPEN)
# robot.move(Move.LINEAR, A8_up)
# robot.move(Move.LINEAR, A8)
# gripper.control(State.CLOSE)
# robot.move(Move.LINEAR, A8_up)
# robot.move(Move.LINEAR, A1_up)
# robot.move(Move.LINEAR, A1)
# gripper.control(State.OPEN)
# robot.move(Move.LINEAR, A1_up)
# robot.move(Move.LINEAR, A1)
# gripper.control(State.CLOSE)
# robot.move(Move.LINEAR, A1_up)
# robot.move(Move.LINEAR, B2_up)
# robot.move(Move.LINEAR, B2)
# gripper.control(State.OPEN)
# robot.move(Move.LINEAR, B2_up)
# robot.move(Move.LINEAR, B2)
# gripper.control(State.CLOSE)
# robot.move(Move.LINEAR, B2_up)
# robot.move(Move.LINEAR, C3_up)
# robot.move(Move.LINEAR, C3)
# gripper.control(State.OPEN)
# robot.move(Move.LINEAR, C3_up)
# robot.move(Move.LINEAR, C3)
# gripper.control(State.CLOSE)
# robot.move(Move.LINEAR, C3_up)
# robot.move(Move.LINEAR, D4_up)
# robot.move(Move.LINEAR, D4)
# gripper.control(State.OPEN)
# robot.move(Move.LINEAR, D4_up)
# robot.move(Move.LINEAR, D4)
# gripper.control(State.CLOSE)
# robot.move(Move.LINEAR, D4_up)
# robot.move(Move.LINEAR, E5_up)
# robot.move(Move.LINEAR, E5)
# gripper.control(State.OPEN)
# robot.move(Move.LINEAR, E5_up)
# robot.move(Move.LINEAR, E5)
# gripper.control(State.CLOSE)
# robot.move(Move.LINEAR, E5_up)
# robot.move(Move.LINEAR, F6_up)
# robot.move(Move.LINEAR, F6)
# gripper.control(State.OPEN)
# robot.move(Move.LINEAR, F6_up)
# robot.move(Move.LINEAR, F6)
# gripper.control(State.CLOSE)
# robot.move(Move.LINEAR, F6_up)
# robot.move(Move.LINEAR, G7_up)
# robot.move(Move.LINEAR, G7)
# gripper.control(State.OPEN)
# robot.move(Move.LINEAR, G7_up)
# robot.move(Move.LINEAR, G7)
# gripper.control(State.CLOSE)
# robot.move(Move.LINEAR, G7_up)
# robot.move(Move.LINEAR, H8_up)
# robot.move(Move.LINEAR, H8)
# gripper.control(State.OPEN)
# robot.move(Move.LINEAR, H8_up)
# robot.move(Move.LINEAR, H8)
# gripper.control(State.CLOSE)
# robot.move(Move.LINEAR, H8_up)
# robot.move(Move.LINEAR, H1_up)
# robot.move(Move.LINEAR, H1)
# gripper.control(State.OPEN)
# robot.move(Move.LINEAR, H1_up)
# robot.move(Move.LINEAR, H1)
# gripper.control(State.CLOSE)
# robot.move(Move.LINEAR, H1_up)
# robot.move(Move.LINEAR, A8_up)
# robot.move(Move.LINEAR, A8)
# gripper.control(State.OPEN)
# robot.move(Move.LINEAR, A8_up)

robot.disconnect()
